name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below so we can help.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Include details such as platform, device, Flutter version, and OS.
      placeholder: e.g. macOS 14, Flutter 3.22.1, Android 13
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Describe the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Paste logs, screenshots, or error messages here.
      render: shell
