name: Feature Request
description: Suggest a new idea or enhancement
title: "[FEATURE] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: motivation
    attributes:
      label: Motivation
      description: |
        Why is this feature important? What problem does it solve?
      placeholder: e.g. "Helps users track their progress over time"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: |
        Describe the feature you'd like to see.
      placeholder: e.g. "Add a new analytics screen that shows trends across attempts..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered other approaches? If so, what were they?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Any additional info, designs, references, or screenshots?
